[package]
name = "utils"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[lib]
name = "utils"
path = "src/main.rs"

[dependencies]
handler.workspace = true
windows.workspace = true