[package]
name = "handler"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[lib]
name = "handler"
path = "src/main.rs"

[dependencies]
tauri.workspace = true
windows.workspace = true
serde_json.workspace = true
tauri-plugin-shell.workspace = true